version: "3.2"

services:
    verysync:
        build:
            context: ./versions/${VERSION:-latest}/${PLATFORM_ARCH:-amd64}
            args:
                - TARGET_PLATFORM_ARCH=${PLATFORM_ARCH:-amd64}
        image: verysync:latest
        ports:
            - "8886:8886"
            - "22330:22330"
            - "443:443"
            - "4222:4222"
            - "22067:22067"
            - "22331:22331/udp"
            - "22027:22027/udp"
            - "22037:22037/udp"
        restart: always
        volumes:
            - type: bind
              source: ./data
              target: /app/var
