name: Docker Image CI

on:
    push:
        tags:
            - v*.*.*

jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v2
            - name: Build the Docker image
              env:
                  TARGET_PLATFORM_OS: linux
                  TARGET_PLATFORM_ARCH: amd64
              run: |
                  export TARGET_VERSION=${GITHUB_REF##*/}
                  docker build . --file Dockerfile --tag "${GITHUB_REPOSITORY}"
            - name: Login Docker Hub
              env:
                  DOCKER_USERNAME: ${{ github.repository_owner }}
                  DOCKER_PASSWORD: ${{ secrets.DOCKER_ACCESS_TOKEN }}
              run: echo -n "${DOCKER_PASSWORD}" | docker login --username "${DOCKER_USERNAME}" --password-stdin
            - name: Publish the Docker image
              run: |
                  docker tag "${GITHUB_REPOSITORY}" "${GITHUB_REPOSITORY}":"${GITHUB_REF##*/}"
                  docker push "${GITHUB_REPOSITORY}"
